name: Maybe deploy to WordPress.org
on:
  push:
    tags:
      - "*"

    branches:
      - main        # Triggers on push to main
permissions:
  contents: write

jobs:
  build_or_publish:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Build # Remove or modify this step as needed
#        run: |
#          npm install
#          npm run build
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Verify Composer version
        run: composer --version

      - name: Configure Git for push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Install composer
        run: composer install --no-dev --optimize-autoloader
      - name: Check if SVN credentials are set
        id: is_svn_credentials_available
        run: |
          if [ -n "${{ secrets.SVN_USERNAME }}" ] && [ -n "${{ secrets.SVN_PASSWORD }}" ]; then
            echo "SVN credentials are set"
            echo "available=true" >> $GITHUB_OUTPUT
          else
            echo "SVN credentials are NOT set"
            echo "available=false" >> $GITHUB_OUTPUT
          fi
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

      - name: WordPress Theme Deploy
        if: steps.is_svn_credentials_available.outputs.available == 'true'
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: creator-mode
      - name: Run only when no SVN credentials are set
        if: steps.is_svn_credentials_available.outputs.available == 'false'
        run: |
          git fetch origin || echo "Unable to fetch branches"
          git checkout prod
          composer install --no-dev --optimize-autoloader
          git diff main || echo "No difference"
          git merge main || echo "No conflict found"
          git add . || echo "No merge conflict resolved"
          git commit -m "Auto-resolved conflicts using 'theirs'" || echo "No conflicts to resolve"
      - name: Push changes
        if: steps.is_svn_credentials_available.outputs.available == 'false'
        run: git push origin prod
